### ISSUE TITLE
A way to automate the resetusb_script

### ISSUE THREAD

**Issue by Kurt1968** [mishta-real/ricoh-sp100#4]
Did anyone find a way to automate the use of the command "./resetusb_script" to avoid doing it for any print? Or any solution to avoid using it at all? I tried using Tea4CUPS but I did not understand how to configure it

**Comment by revisitor** [comment]
I had that problem too. Try repeating steps 2 and 3 from here:
https://wiki.ubuntu.com/DebuggingPrintingProblems#USB_printer_does_not_print_or_prints_garbage

Replace _\<queue\>_ with your printer name from CUPS. It worked for me, and I no longer need to run _resetusb_.

**Comment by Kurt1968** [comment]
Thank you so much,IT WORKS! You saved me, I've been struggling with this issue for months...I was thinking about getting a new printer. You should really put those info inside the README file to allow people to see it at a first glance. Anyway, is there a way to use the double side print feature?

**Comment by revisitor** [comment]
Glad it helped too. I have updated the README.
I would really like to add duplex printing support, but I can't because my printer (SP 100SU) doesn't have it. Even if I tried to add that, I would not be able to test it.
